const usecasePresets = {
  advertisements: {
    id: "advertisements",
    title: "Advertisements",
    description: "High energy cuts, motion text, voiceover pacing",
    variants: {
      modern_product_ad: {
        id: "modern_product_ad",
        title: "Modern Product Advertisement",
        aspectRatio: "16:9",
        tone: "Cinematic / Premium",
        contextKeys: {
          grade: "modern_digital",
          lighting: "high_key_studio",
          location: "shallow_dof",
          wardrobe: "minimalist_modern",
          sound: "dramatic_music",
        },
        defaultHighLevel:
          "A sleek, cinematic ad introducing a premium product with macro beauty shots, minimal text overlays, and refined motion typography.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Macro glide over product surface with specular highlights",
            camera: "Slow dolly, 50mm",
            overlays: [],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Close-up interaction (hand touch/press/tilt), shallow DOF bokeh",
            camera: "Locked macro, 85mm",
            overlays: [],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Wide reveal of desk/setup; headline text callout",
            camera: "Crane up, parallax",
            overlays: ['Headline: "Designed to perform."'],
          },
        ],
        defaultDialogue: [
          { speaker: "Narrator", text: "Precision you can feel." },
          { speaker: "Sound Effect", text: "[Subtle mechanical clicks under ambient score]" },
        ],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      vintage_90s_ad: {
        id: "vintage_90s_ad",
        title: "90s Tech Commercial",
        aspectRatio: "4:3",
        tone: "Retro / Infomercial",
        contextKeys: {
          grade: "vintage_8mm",
          lighting: "harsh_fluorescent",
          location: "medium_eye_level",
          wardrobe: "streetwear_urban",
          sound: "retro_analog",
        },
        defaultHighLevel:
          "A playful retro commercial with VHS vibes, bold callouts, and enthusiastic VO celebrating the 'future of computing'.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Static product table shot with cheesy starburst graphic",
            camera: "Tripod, 35mm",
            overlays: ["NEW!"],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Smiling presenter demo at eye level; jump zooms",
            camera: "Snap zooms, 50mm",
            overlays: ["On-screen bullet points"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Closing slate with big logo and toll-free lower-third",
            camera: "Static",
            overlays: ["Call now!"],
          },
        ],
        defaultDialogue: [
          { speaker: "Narrator", text: "From the future of computing comes a breakthrough in conversation." },
        ],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      chaotic_japanese_ad: {
        id: "chaotic_japanese_ad",
        title: "Chaotic Japanese Ad",
        aspectRatio: "16:9",
        tone: "Hyper / Maximalist",
        contextKeys: {
          grade: "technicolor",
          lighting: "neon_artificial",
          location: "wide_establishing",
          wardrobe: "vibrant_colorful",
          sound: "action_intense",
        },
        defaultHighLevel:
          "Maximalist, high-energy, text-slam chaos with neon typographic bursts, quick cuts, and surreal micro-scenes.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Neon city alley; kinetic text blasts synced to beats",
            camera: "Handheld whip pans",
            overlays: ["巨 大 爆 発 的"],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Mascot character sprint past product placements",
            camera: "Tracking, 24mm",
            overlays: ["Flash price tags"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Final staccato montage; logo impact and tagline",
            camera: "Rapid smash cuts",
            overlays: ["Logo + Tagline"],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  app_promotions: {
    id: "app_promotions",
    title: "App Promotions",
    description: "Vertical aspect ratio, upbeat tone, human actors",
    variants: {
      tiktok_app_demo: {
        id: "tiktok_app_demo",
        title: "TikTok-Style App Demo",
        aspectRatio: "9:16",
        tone: "Upbeat / Conversational",
        contextKeys: {
          grade: "modern_digital",
          lighting: "high_key_studio",
          location: "handheld_documentary",
          wardrobe: "streetwear_urban",
          sound: "dialogue_driven",
        },
        defaultHighLevel:
          "Fast-paced vertical promo featuring a creator speaking to camera, cutaways to UI screenshots, and bold captions.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Selfie cam intro; creator hooks the viewer",
            camera: "Handheld selfie, 24–35mm",
            overlays: ["Captions: large, stacked"],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "UI overlay sequences demonstrating core features",
            camera: "Locked, screen comps",
            overlays: ["Feature callouts"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Before/after reaction; CTA end card",
            camera: "Handheld, push-in",
            overlays: ["CTA: Download now"],
          },
        ],
        defaultDialogue: [
          { speaker: "Host", text: "This literally saved me 20 minutes every day—here's how it works." },
        ],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      ui_showcase: {
        id: "ui_showcase",
        title: "UI Showcase",
        aspectRatio: "16:9",
        tone: "Clean / Explanatory",
        contextKeys: {
          grade: "modern_digital",
          lighting: "overcast_diffused",
          location: "wide_establishing",
          wardrobe: "minimalist_modern",
          sound: "minimal_sound",
        },
        defaultHighLevel:
          "Sleek UI animations, magnified feature highlights, and minimal narration focused on clarity and benefits.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Hero screen with gentle parallax; feature 1 focus",
            camera: "Slow dolly",
            overlays: ["Feature 1 label"],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Cursor interactions zoom; feature 2 animation",
            camera: "Macro UI crop",
            overlays: ["Feature 2 label"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "End frame with app icon grid and CTA",
            camera: "Static",
            overlays: ["Available on iOS/Android"],
          },
        ],
        defaultDialogue: [{ speaker: "Narrator", text: "Designed for speed, built for focus." }],
        output: { preferred: "json", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  company_promos: {
    id: "company_promos",
    title: "Company / Industrial Promos",
    description: "Professional voiceover, cinematic montage, brand tone",
    variants: {
      b2b_industrial: {
        id: "b2b_industrial",
        title: "B2B Tech / Industrial",
        aspectRatio: "16:9",
        tone: "Professional / Credible",
        contextKeys: {
          grade: "documentary",
          lighting: "overcast_diffused",
          location: "wide_establishing",
          wardrobe: "business_corporate",
          sound: "ambient_environmental",
        },
        defaultHighLevel:
          "A credible B2B montage with brand color accents, facility cutaways, and mission-driven captions.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Facility exterior establishing with subtle brand blue accents",
            camera: "Aerial/slow rise",
            overlays: [],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Operators and machinery macro details",
            camera: "Macro, shallow DOF",
            overlays: ["Capability callouts"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Logo + mission statement lower-third, calm motion",
            camera: "Static/clean comp",
            overlays: ["Mission statement"],
          },
        ],
        defaultDialogue: [
          { speaker: "Narrator", text: "Delivering critical capabilities through trusted partnerships." },
        ],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  product_commercials: {
    id: "product_commercials",
    title: "Product Commercials",
    description: "Macro shots, slow pans, lighting emphasis",
    variants: {
      tech_product: {
        id: "tech_product",
        title: "Tech Product",
        aspectRatio: "16:9",
        tone: "Moody / Premium",
        contextKeys: {
          grade: "imax_scale",
          lighting: "neon_artificial",
          location: "shallow_dof",
          wardrobe: "minimalist_modern",
          sound: "dramatic_music",
        },
        defaultHighLevel: "Moody hero piece with glossy reflections, elegant close-ups, and minimal copy.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Edge lighting skims the chassis; logo glints",
            camera: "Slider micro-move",
            overlays: [],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Port/feature macro with animated line art",
            camera: "Macro, focus rack",
            overlays: ["Feature label"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Wide hero shot; tagline appears center",
            camera: "Static, symmetrical",
            overlays: ["Tagline"],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      furniture_lifestyle: {
        id: "furniture_lifestyle",
        title: "Furniture / Lifestyle",
        aspectRatio: "16:9",
        tone: "Comfort / Tactile",
        contextKeys: {
          grade: "modern_digital",
          lighting: "golden_hour",
          location: "medium_eye_level",
          wardrobe: "minimalist_modern",
          sound: "diegetic_source",
        },
        defaultHighLevel:
          "Warm lifestyle vignette showing comfort features with tactile interactions and soft natural light.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 3,
            description: "Hand pressing cushion; fabric texture detail",
            camera: "Macro, 85mm",
            overlays: [],
          },
          {
            start_sec: 3,
            duration_sec: 3,
            description: "Recline feature shown in a cozy living space",
            camera: "Medium, slow dolly",
            overlays: ["152° recline"],
          },
          {
            start_sec: 6,
            duration_sec: 4,
            description: "Smiling user at desk; soft sun flare; logo end card",
            camera: "Wide, static",
            overlays: ["Logo + CTA"],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  live_news_ted: {
    id: "live_news_ted",
    title: "Live / News / TED",
    description: "Realistic camera jitter, authentic dialogue tone",
    variants: {
      livestream_sim: {
        id: "livestream_sim",
        title: "Livestream Simulation",
        aspectRatio: "9:16",
        tone: "Raw / Spontaneous",
        contextKeys: {
          grade: "documentary",
          lighting: "overcast_diffused",
          location: "handheld_documentary",
          wardrobe: "practical_props",
          sound: "dialogue_driven",
        },
        defaultHighLevel:
          "Vertical 'live' feed with chat overlays, handheld movement, and spur-of-the-moment narration.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Runner selfie-cam chaos; chat bubbles popping",
            camera: "Handheld selfie",
            overlays: ["LIVE badge, chat feed"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "Escalation beat; dramatic reaction; signal glitches",
            camera: "Whip pans / reframing",
            overlays: ["Reconnect spinner"],
          },
        ],
        defaultDialogue: [{ speaker: "Host", text: "We just hit 1,000 viewers—this is wild!" }],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      ted_talk: {
        id: "ted_talk",
        title: "TED Talk",
        aspectRatio: "16:9",
        tone: "Thoughtful / Inspirational",
        contextKeys: {
          grade: "modern_digital",
          lighting: "high_key_studio",
          location: "medium_eye_level",
          wardrobe: "minimalist_modern",
          sound: "dialogue_driven",
        },
        defaultHighLevel:
          "Speaker on stage with confident pacing, animated lower-thirds for key points, and restrained camera moves.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 5,
            description: "Medium speaker on stage; animated title lower-third",
            camera: "Tripod, 50mm slow push",
            overlays: ["Talk title"],
          },
          {
            start_sec: 5,
            duration_sec: 5,
            description: "Cutaway to audience reaction, return to speaker with key quote",
            camera: "Cutaway + return",
            overlays: ["Pull quote"],
          },
        ],
        defaultDialogue: [
          { speaker: "Speaker", text: "We can build scalable systems that learn safely and adapt over time." },
        ],
        output: { preferred: "json", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      news_segment: {
        id: "news_segment",
        title: "News Segment",
        aspectRatio: "16:9",
        tone: "Authoritative / Breaking",
        contextKeys: {
          grade: "documentary",
          lighting: "harsh_fluorescent",
          location: "over_shoulder",
          wardrobe: "business_corporate",
          sound: "dialogue_driven",
        },
        defaultHighLevel: "Anchor-led package with OTS graphics, scrolling ticker, and B-roll cutaways.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Anchor desk; OTS graphic panel; ticker crawl",
            camera: "Static, eye level",
            overlays: ["Ticker, OTS"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "B-roll montage supporting the story; return to anchor for sign-off",
            camera: "Mixed cuts",
            overlays: ["Lower-third"],
          },
        ],
        defaultDialogue: [
          { speaker: "Anchor", text: "We're following developing details—more updates as they come in." },
        ],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  social_pov: {
    id: "social_pov",
    title: "Social / POV",
    description: "Handheld feel, dynamic angles, personal tone",
    variants: {
      selfie_vlog: {
        id: "selfie_vlog",
        title: "Selfie Vlog",
        aspectRatio: "9:16",
        tone: "Personal / Casual",
        contextKeys: {
          grade: "documentary",
          lighting: "overcast_diffused",
          location: "first_person_pov",
          wardrobe: "practical_props",
          sound: "dialogue_driven",
        },
        defaultHighLevel: "POV selfie vlog with candid delivery, quick jump-cuts, and location ambience.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Selfie intro, walking; jump-cuts on sentences",
            camera: "Handheld selfie",
            overlays: ["Auto captions"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "Cutaways to B-roll (street, object, reaction); back to selfie CTA",
            camera: "Handheld + B-roll",
            overlays: [],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      bodycam_security: {
        id: "bodycam_security",
        title: "Body Cam / Security Footage",
        aspectRatio: "16:9",
        tone: "Gritty / Realistic",
        contextKeys: {
          grade: "documentary",
          lighting: "overcast_diffused",
          location: "handheld_documentary",
          wardrobe: "practical_props",
          sound: "ambient_environmental",
        },
        defaultHighLevel:
          "Low-fidelity, timestamped body-cam angle with authentic mic handling noise and quick reframes.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 5,
            description: "Single long take approaching subject; timestamp overlay",
            camera: "Chest-mounted shake",
            overlays: ["Timestamp, 'REC'"],
          },
          {
            start_sec: 5,
            duration_sec: 5,
            description: "De-escalation moment; lens flare/smear; exit frame",
            camera: "Handheld retreat",
            overlays: [],
          },
        ],
        defaultDialogue: [{ speaker: "Officer", text: "Easy there—drop it for me. Thank you." }],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  concept_games: {
    id: "concept_games",
    title: "Concept Games & Demos",
    description: "3D-like render, game UI overlay, sound design",
    variants: {
      gameplay_trailer: {
        id: "gameplay_trailer",
        title: "Gameplay Trailer (Concept)",
        aspectRatio: "16:9",
        tone: "Epic / Kinetic",
        contextKeys: {
          grade: "imax_scale",
          lighting: "cool_moonlight",
          location: "wide_establishing",
          wardrobe: "futuristic_elements",
          sound: "action_intense",
        },
        defaultHighLevel:
          "Cinematic gameplay concept in a forest at night against a dinosaur, with HUD hints and impactful SFX.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Night forest prowl; HUD crosshair blink; breath frost",
            camera: "Steadicam, 24mm",
            overlays: ["HUD reticle"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "Monster reveal; reload animation; victorious tagline",
            camera: "Whip pan + tilt",
            overlays: ['"One less hunter."'],
          },
        ],
        defaultDialogue: [{ speaker: "Player", text: "There you are. Reloading—moving in." }],
        output: { preferred: "json", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  entertainment_parody: {
    id: "entertainment_parody",
    title: "Entertainment / Parody",
    description: "Dialogue-driven, comedic, stylized realism",
    variants: {
      tv_show_scene: {
        id: "tv_show_scene",
        title: "TV Show Scene",
        aspectRatio: "16:9",
        tone: "Dramatic / Reality",
        contextKeys: {
          grade: "modern_digital",
          lighting: "moody_twilight",
          location: "over_shoulder",
          wardrobe: "vibrant_colorful",
          sound: "dialogue_driven",
        },
        defaultHighLevel: "Dramatic confrontation in a villa courtyard with reaction shots and reality-TV pacing.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 5,
            description: "Over-shoulder accusation; rack focus to reaction",
            camera: "OTS, 50mm",
            overlays: ["Lower-third names"],
          },
          {
            start_sec: 5,
            duration_sec: 5,
            description: "Cutaway whispers; host interjects; beat-to-black",
            camera: "Multi-cam intercut",
            overlays: [],
          },
        ],
        defaultDialogue: [{ speaker: "Contestant", text: "Are you kidding me right now?" }],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      ai_episode_cartoon: {
        id: "ai_episode_cartoon",
        title: "AI Episode / Cartoon",
        aspectRatio: "16:9",
        tone: "Comedic / Meta",
        contextKeys: {
          grade: "technicolor",
          lighting: "high_key_studio",
          location: "wide_establishing",
          wardrobe: "high_fashion_editorial",
          sound: "dramatic_music",
        },
        defaultHighLevel: "Animated-style episode with punchy dialogue, fast cuts, and surreal transitions.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Portal opens; duo steps into neon lab",
            camera: "Wide, snap zoom",
            overlays: ["Wacky captions"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "Gag montage and freeze-frame end card",
            camera: "Rapid cuts",
            overlays: ["Series logo"],
          },
        ],
        defaultDialogue: [{ speaker: "Character A", text: "OpenAI finally dropped the update—look at this!" }],
        output: { preferred: "json", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },

  creative_experiments: {
    id: "creative_experiments",
    title: "Creative Experiments",
    description: "Novel camera perspectives, humor-driven pacing",
    variants: {
      doorbell_cam: {
        id: "doorbell_cam",
        title: "Doorbell / Fisheye Camera",
        aspectRatio: "16:9",
        tone: "Quirky / Situational",
        contextKeys: {
          grade: "documentary",
          lighting: "overcast_diffused",
          location: "high_angle_down",
          wardrobe: "practical_props",
          sound: "ambient_environmental",
        },
        defaultHighLevel: "Fish-eye porch cam perspective with comedic beats and text pop-ups.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 5,
            description: "Courier drops package; fisheye distortion; chime",
            camera: "Fixed high angle",
            overlays: ["Ding-dong!"],
          },
          {
            start_sec: 5,
            duration_sec: 5,
            description: "Unexpected twist; pop-up warning; cut",
            camera: "Fixed",
            overlays: ["Motion detected"],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
      fake_live_event: {
        id: "fake_live_event",
        title: "Fake Live Spectacle",
        aspectRatio: "9:16",
        tone: "Spectacle / Viral",
        contextKeys: {
          grade: "imax_scale",
          lighting: "neon_artificial",
          location: "handheld_documentary",
          wardrobe: "vibrant_colorful",
          sound: "binaural_immersive",
        },
        defaultHighLevel: "Over-the-top 'live' stunt with audience chat overlays and surprising crowd reactions.",
        defaultShots: [
          {
            start_sec: 0,
            duration_sec: 4,
            description: "Hype intro; chat explodes; reveal tease",
            camera: "Handheld push",
            overlays: ["LIVE, chat"],
          },
          {
            start_sec: 4,
            duration_sec: 6,
            description: "Release moment; chaotic reactions; cliffhanger end",
            camera: "Whip pans",
            overlays: ["Viewer counter surges"],
          },
        ],
        defaultDialogue: [],
        output: { preferred: "text", options: ["text", "json"] },
        constraints: { maxDurationSec: 10 },
      },
    },
  },
}
